/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import data from "../data/generated/cba-site-data.json";

const manager = (name:string) => data.managers.find(m=>m.fullName===name)!;
test("headline career and postseason totals reconcile",()=>{assert.equal(manager("Will Leafstedt").wins,73);assert.equal(manager("Kelbey Heider").championships,4);assert.equal(manager("Kelbey Heider").playoffWins,9);assert.equal(manager("Tim Switzer").pointsFor,12976.2);assert.equal(manager("Cody Leslie").seasonHistory.find(s=>s.year===2024)?.wins,13);assert.equal(manager("Cody Leslie").longestWinningStreak,17);assert.equal(manager("Austin Ketter").longestLosingStreak,11)});
test("career regular totals and playoff totals exclude consolation",()=>{const regularGames=854,winnersBracketGames=45;assert.equal(data.managers.reduce((n,m)=>n+m.wins,0),regularGames);assert.equal(data.managers.reduce((n,m)=>n+m.losses,0),regularGames);assert.equal(data.managers.reduce((n,m)=>n+m.playoffWins,0),winnersBracketGames);assert.equal(data.managers.reduce((n,m)=>n+m.playoffLosses,0),winnersBracketGames);assert.equal(data.h2h.reduce((n,r)=>n+r.meetings,0),1034*2)});
test("record book excludes consolation anomalies",()=>{const lowest=data.records.find(r=>r.label==="Lowest single-game score")!;const blowout=data.records.find(r=>r.label==="Biggest blowout")!;const closest=data.records.find(r=>r.label==="Closest game")!;assert.equal(lowest.value,7.6);assert.equal(lowest.managerName,"Peter Ganz");assert.equal(blowout.value,105.92);assert.equal(blowout.managerName,"Joe Smith");assert.equal(closest.value,0.02);assert.equal(closest.managerName,"Shawn Smith")});
test("all championship finals match ESPN winners bracket finalists",()=>{for(const championship of data.championships){const raw=JSON.parse(readFileSync(`data/raw/${championship.year}.json`,"utf8"));const champion=raw.teams.find((t:any)=>t.rankCalculatedFinal===1);const runner=raw.teams.find((t:any)=>t.rankCalculatedFinal===2);const final=raw.schedule.find((g:any)=>g.home&&g.away&&g.playoffTierType==="WINNERS_BRACKET"&&[g.home.teamId,g.away.teamId].includes(champion.id)&&[g.home.teamId,g.away.teamId].includes(runner.id));assert.ok(final);const cs=final.home.teamId===champion.id?final.home.totalPoints:final.away.totalPoints;const rs=final.home.teamId===runner.id?final.home.totalPoints:final.away.totalPoints;assert.equal(championship.championScore,cs);assert.equal(championship.runnerUpScore,rs)}});
test("raw matchup ledger has no duplicates, missing opponents, ties, or 2026 completions",()=>{const keys=new Set<string>();for(let year=2017;year<=2026;year++){const raw=JSON.parse(readFileSync(`data/raw/${year}.json`,"utf8"));for(const game of raw.schedule.filter((g:any)=>g.home&&g.away&&["HOME","AWAY","TIE"].includes(g.winner))){const key=`${year}:${game.id}`;assert.equal(keys.has(key),false);keys.add(key);assert.notEqual(game.home.teamId,null);assert.notEqual(game.away.teamId,null);assert.notEqual(game.home.totalPoints,game.away.totalPoints);if(year===2026)assert.fail("2026 completed game leaked into ledger")}}});
