import Link from "next/link";
import { notFound } from "next/navigation";
import { SeasonSelector } from "@/components/season-selector";
import { completedRecapYears, seasonRecaps } from "@/data/season-recaps";
import { cbaData } from "@/data/real";
import type { RecapGame, RecapSeasonFacts } from "@/types/season-recap";

export function generateStaticParams(){return [...completedRecapYears,2026].map(year=>({year:String(year)}))}
export async function generateMetadata({params}:{params:Promise<{year:string}>}){const{year}=await params;return{title:`${year} Season Recap`}}

export default async function SeasonRecapPage({params}:{params:Promise<{year:string}>}){
  const year=Number((await params).year);
  if(year===2026)return <InProgress/>;
  const recap=seasonRecaps.get(year); if(!recap||!completedRecapYears.includes(year as never))notFound();
  const {facts,editorial}=recap;
  const punishment=cbaData.punishmentHistory.find(result=>result.year===year); if(!punishment)notFound();
  const final=facts.playoffs.find(game=>game.week===facts.championshipWeek&&[game.homeManager,game.awayManager].includes(facts.champion.manager)&&[game.homeManager,game.awayManager].includes(facts.runnerUp.manager));
  const rounds=Map.groupBy(facts.playoffs,game=>game.week);
  const awards=buildAwards(facts);
  return <>
    <header className="container py-10 md:py-14">
      <div className="flex flex-wrap items-center justify-between gap-4"><p className="eyebrow">Season Recap</p><SeasonSelector year={year} years={completedRecapYears}/></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_440px] lg:items-end"><div><h1 className="display text-5xl leading-none sm:text-7xl">{year} CBA Season</h1><p className="mt-4 max-w-2xl text-lg leading-7 text-[#a5adb6]">The standings, bracket, receipts, and appropriately limited commentary.</p></div><div className="surface grid grid-cols-2 gap-4 p-5"><div><p className="eyebrow">CBA Champion</p><p className="mt-2 text-xl font-bold text-[#dfb65f]">{facts.champion.manager}</p><p className="text-xs text-[#929ba5]">{facts.champion.teamName}</p></div><div className="border-l border-[#433238] pl-4"><p className="eyebrow text-[#c48a83]">Stupidest Loser</p><p className="mt-2 text-xl font-bold">{punishment.managerName}</p><p className="text-xs text-[#929ba5]">{punishment.teamName}</p></div><div className="col-span-2 border-t border-[#292f38] pt-4"><p className="text-xs text-[#929ba5]">Championship score · over {facts.runnerUp.manager}</p><p className="stat-number mt-1 text-3xl">{facts.champion.score.toFixed(2)}–{facts.runnerUp.score.toFixed(2)}</p></div></div></div>
    </header>
    <div className="container space-y-14">
      <Section title="The Season in Review" kicker="The yearbook"><div className="max-w-3xl space-y-5 text-[1.02rem] leading-8 text-[#c0c6cc]">{editorial.review.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></Section>
      <Section title="Final Standings" kicker="Regular season"><div className="table-wrap"><table><thead><tr><th>Manager</th><th>Team</th><th>W-L</th><th>PF</th><th>PA</th><th>Postseason</th></tr></thead><tbody>{facts.standings.map(row=><tr key={row.manager}><td className="font-bold text-white">{row.manager}</td><td>{row.teamName}</td><td>{row.wins}-{row.losses}{row.ties?`-${row.ties}`:""}</td><td>{row.pointsFor.toFixed(2)}</td><td>{row.pointsAgainst.toFixed(2)}</td><td>{row.playoffResult}</td></tr>)}</tbody></table></div></Section>
      <Section title="Playoff Results" kicker="Championship bracket"><div className="grid gap-5 lg:grid-cols-3">{[...rounds.entries()].map(([week,games],index)=><article className="surface p-5" key={week}><p className="eyebrow">{index===rounds.size-1?"Championship":index===rounds.size-2?"Semifinals":"Opening Round"} · Week {week}</p><div className="mt-4 divide-y divide-[#292f38]">{games.map(game=><GameLine game={game} key={game.matchupId}/>)}</div></article>)}</div></Section>
      <Section title="Championship" kicker="The last word"><div className="surface grid gap-7 p-6 md:grid-cols-[260px_1fr] md:p-8"><div><p className="eyebrow">Final · Week {facts.championshipWeek}</p><p className="mt-4 text-2xl font-extrabold text-[#dfb65f]">{facts.champion.manager}</p><p className="text-sm text-[#929ba5]">{facts.champion.teamName}</p><p className="stat-number mt-4 text-4xl">{facts.champion.score.toFixed(2)}</p><p className="my-2 text-xs text-[#727b85]">over</p><p className="text-lg font-bold">{facts.runnerUp.manager} · {facts.runnerUp.score.toFixed(2)}</p></div><div><p className="text-base leading-8 text-[#c0c6cc]">{editorial.championship}</p>{final&&<p className="mt-5 text-sm text-[#929ba5]">Official margin: {final.margin.toFixed(2)} points.</p>}</div></div></Section>
      <Section title="Stupidest Loser" kicker="Punishment Bracket"><div className="surface grid gap-7 border-[#54363b] p-6 md:grid-cols-[280px_1fr] md:p-8"><div><p className="eyebrow text-[#c48a83]">Final assignment · Week {punishment.finalPunishmentMatchup.week}</p><p className="mt-4 text-2xl font-extrabold">{punishment.managerName}</p><p className="text-sm text-[#929ba5]">{punishment.teamName}</p><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-[#7f8994]">Regular season</dt><dd className="mt-1 font-bold">{punishment.regularSeasonRecord.wins}-{punishment.regularSeasonRecord.losses}{punishment.regularSeasonRecord.ties?`-${punishment.regularSeasonRecord.ties}`:""} · #{punishment.regularSeasonFinish}</dd></div><div><dt className="text-[#7f8994]">Punishment record</dt><dd className="mt-1 font-bold">{punishment.consolationWins}-{punishment.consolationLosses}{punishment.consolationTies?`-${punishment.consolationTies}`:""}</dd></div></dl></div><div><p className="text-base leading-8 text-[#c0c6cc]">{editorial.stupidestLoser}</p><p className="mt-5 text-sm text-[#929ba5]">Final: {punishment.managerName} {punishment.finalScore.toFixed(2)} · {punishment.finalOpponentName} {punishment.opponentScore.toFixed(2)}</p><p className="mt-3 text-xs leading-6 text-[#78818b]">Path: {punishment.consolationMatchups.map(game=>`Week ${game.week} ${game.result} vs ${game.opponentName} (${game.score.toFixed(2)}-${game.opponentScore.toFixed(2)})`).join(" · ")}</p></div></div></Section>
      <Section title="Season Superlatives" kicker="Factually earned"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{awards.map(award=><article className="surface p-5" key={award.title}><p className="eyebrow">{award.title}</p><p className="mt-3 text-lg font-bold">{award.manager}</p><p className="mt-1 text-sm leading-6 text-[#9da5ae]">{award.fact}</p></article>)}</div></Section>
      <Section title="How Everyone Finished" kicker="Manager by manager"><div className="grid gap-4 md:grid-cols-2">{facts.standings.map((standing,index)=><article className="surface p-5" key={standing.manager}><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-bold">{standing.manager}</h3><p className="text-sm text-[#929ba5]">{standing.teamName}</p></div><span className="stat-number text-[#7f8994]">#{index+1}</span></div><p className="mt-4 text-sm leading-6 text-[#bdc3c9]">{editorial.managerSummaries[standing.manager]}</p></article>)}</div></Section>
      <Section title="Season Numbers" kicker="At a glance"><div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{[["Eligible games",facts.numbers.totalEligibleCompletedGames],["Regular-season games",facts.numbers.completedRegularSeasonGames],["Average team score",facts.numbers.averageTeamScore.toFixed(2)],["Playoff teams",facts.numbers.playoffTeams],["Closest margin",facts.superlatives.closestEligibleGame.margin.toFixed(2)]].map(([label,value])=><div className="surface p-5" key={label}><p className="stat-number text-3xl text-[#dfb65f]">{value}</p><p className="mt-2 text-xs text-[#929ba5]">{label}</p></div>)}</div></Section>
    </div>
  </>;
}

function Section({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <section><p className="eyebrow">{kicker}</p><h2 className="display mb-6 mt-2 text-3xl sm:text-4xl">{title}</h2>{children}</section>}
function GameLine({game}:{game:RecapGame}){const homeWon=game.winner===game.homeManager;return <div className="py-4 text-sm"><div className="flex justify-between gap-3"><span className={homeWon?"font-bold text-white":"text-[#9da5ae]"}>{game.homeManager}</span><b>{game.homeScore.toFixed(2)}</b></div><div className="mt-2 flex justify-between gap-3"><span className={!homeWon?"font-bold text-white":"text-[#9da5ae]"}>{game.awayManager}</span><b>{game.awayScore.toFixed(2)}</b></div></div>}
const points=(value:number)=>value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
function buildAwards(f:RecapSeasonFacts){const s=f.superlatives;const awards=[{title:"Regular Season Tryhard",manager:s.bestRecord.manager,fact:`${s.bestRecord.wins}-${s.bestRecord.losses}${s.bestRecord.ties?`-${s.bestRecord.ties}`:""}, best regular-season record.`},{title:"Points Merchant",manager:s.mostPoints.manager,fact:`${points(s.mostPoints.pointsFor)} regular-season points.`},{title:"Weekly Ceiling",manager:s.highestScore.manager,fact:`${points(s.highestScore.score)} points in Week ${s.highestScore.week}.`},{title:"Weekly Crime Scene",manager:s.lowestEligibleScore.manager,fact:`${points(s.lowestEligibleScore.score)} eligible points in Week ${s.lowestEligibleScore.week}.`},{title:"Call It Early",manager:s.biggestRegularSeasonBlowout.winner,fact:`${points(s.biggestRegularSeasonBlowout.margin)}-point regular-season win in Week ${s.biggestRegularSeasonBlowout.week}.`},{title:"Cardiac Award",manager:s.closestEligibleGame.winner,fact:`Won by ${points(s.closestEligibleGame.margin)} points in Week ${s.closestEligibleGame.week}.`},{title:"Heater",manager:s.longestWinningStreak.manager,fact:`${s.longestWinningStreak.streak} straight regular-season wins.`}];if(s.highestScoringNonPlayoffTeam)awards.push({title:"Points Without a Bracket",manager:s.highestScoringNonPlayoffTeam.manager,fact:`${points(s.highestScoringNonPlayoffTeam.pointsFor)} points while missing the championship bracket.`});return awards}

function InProgress(){return <section className="container py-20"><p className="eyebrow">Current season</p><h1 className="display mt-4 text-5xl sm:text-7xl">2026 is still in progress.</h1><p className="mt-5 max-w-xl text-lg text-[#a5adb6]">The receipts are still being collected. CBA Champion: TBD. Stupidest Loser: TBD.</p><Link href="/" className="mt-8 inline-flex min-h-11 items-center rounded-lg bg-[#d6a84b] px-5 font-bold text-[#17130b]">Back to the current season</Link></section>}
