export interface GameRecord { year: number; week: number; score: number; opponentScore: number; margin: number }
export interface SeasonHistory { year:number; complete:boolean; espnTeamId:number; teamName:string; abbreviation:string; wins:number; losses:number; ties:number; winPercentage:number; pointsFor:number; pointsAgainst:number; pointDifferential:number; finalStanding:number|null; playoffAppearance:boolean; playoffWins:number; playoffLosses:number; playoffResult:string; champion:boolean }
export interface CbaManager { id:string; slug:string; fullName:string; status:"active"|"inactive"; espnAliases:string[]; firstSeason:number; lastSeason:number; seasonsPlayed:number; wins:number; losses:number; ties:number; winPercentage:number; pointsFor:number; pointsAgainst:number; averagePointsFor:number; averagePointsAgainst:number; pointDifferential:number; playoffAppearances:number; playoffWins:number; playoffLosses:number; playoffWinPercentage:number; finalsAppearances:number; championships:number; championshipLosses:number; lastChampionship:number|null; championshipSeasons:number[]; bestSeason:SeasonHistory|null; worstSeason:SeasonHistory|null; highestScoringSeason:SeasonHistory|null; lowestScoringSeason:SeasonHistory|null; biggestWin:GameRecord|null; worstLoss:GameRecord|null; highestScore:GameRecord|null; lowestScore:GameRecord|null; longestWinningStreak:number; longestLosingStreak:number; seasonHistory:SeasonHistory[]; nemesis:string|null; favoriteOpponent:string|null }
export interface H2HRecord { managerId:string; opponentId:string; wins:number; losses:number; ties:number; winPercentage:number; meetings:number; pointsFor:number; pointsAgainst:number; averageScore:number; averageOpponentScore:number; pointDifferential:number; biggestWin:GameRecord|null; worstLoss:GameRecord|null; highestScore:GameRecord|null; lowestScore:GameRecord|null; currentStreak:string; longestWinningStreak:number }
export interface ChampionshipRecord { year:number; championManagerId:string; championName:string; championTeamName:string; runnerUpManagerId:string; runnerUpName:string; runnerUpTeamName:string; championScore:number; runnerUpScore:number; week:number }
export interface LeagueRecord { label:string; managerId:string; managerName:string; value:number; year?:number; week?:number }
export interface RivalrySummary extends H2HRecord { label:string }
export interface Rivalries { methodology:string; mostPlayed:RivalrySummary; closest:RivalrySummary; mostOneSided:RivalrySummary; highestScoring:RivalrySummary; longestActiveWinningStreak:RivalrySummary }
export interface CbaSiteData { generatedAt:string; provisional:boolean; league:{name:string;espnLeagueId:number;firstSeason:number;currentSeason:number}; managers:CbaManager[]; championships:ChampionshipRecord[]; h2h:H2HRecord[]; rivalries:Rivalries; records:LeagueRecord[]; currentStandings:Array<{managerId:string;managerName:string;espnTeamId:number;teamName:string;abbreviation:string;wins:number;losses:number;ties:number;pointsFor:number;pointsAgainst:number}>; anomalies:string[] }
