import Link from "next/link";
import { BannerRack } from "@/components/championship-banner";
import { SectionHeading } from "@/components/section-heading";
import { DataCard } from "@/components/data-card";
import { demoChampionships, demoStandings } from "@/data/mock";

export default function Home() { return <>
  <section className="container grid min-h-[540px] items-center gap-12 py-16 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow mb-5">Established 2017 · The official archive</p><h1 className="display text-[clamp(5rem,16vw,11rem)] leading-[.72]">CBA</h1><p className="display mt-5 max-w-2xl text-3xl leading-none text-[#aeb9bf] md:text-5xl">Every season. Every rivalry. Every name in the rafters.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/history" className="bg-[#d5a846] px-5 py-3 text-xs font-black uppercase tracking-widest text-black">Enter the archive</Link><Link href="/standings" className="border border-[#596770] px-5 py-3 text-xs font-black uppercase tracking-widest">View all-time table</Link></div></div><div className="surface relative overflow-hidden p-7"><p className="eyebrow">League file</p><div className="mt-8 grid grid-cols-2 gap-px bg-[#263442]"><div className="bg-[#101820] p-5"><b className="stat-number text-4xl">273644</b><p className="mt-1 text-xs text-[#8c99a1]">ESPN League ID</p></div><div className="bg-[#101820] p-5"><b className="stat-number text-4xl">2017</b><p className="mt-1 text-xs text-[#8c99a1]">Inaugural season</p></div><div className="bg-[#101820] p-5"><b className="stat-number text-4xl">14</b><p className="mt-1 text-xs text-[#8c99a1]">Current managers</p></div><div className="bg-[#101820] p-5"><b className="stat-number text-4xl">∞</b><p className="mt-1 text-xs text-[#8c99a1]">Old grudges</p></div></div></div></section>
  <section className="border-y border-[#263442] bg-[#090e13] py-14"><div className="container"><SectionHeading kicker="The immortals" aside={<span className="demo-badge">Names pending import</span>}>Championship Rafters</SectionHeading><BannerRack championships={demoChampionships}/></div></section>
  <section className="container py-16"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><SectionHeading kicker="Current season" aside={<span className="demo-badge">Demo</span>}>The Table</SectionHeading><div className="surface divide-y divide-[#24313b]">{demoStandings.slice(0,6).map((r,i)=><div key={r.manager.id} className="grid grid-cols-[35px_1fr_auto_auto] items-center gap-4 px-5 py-4"><b className="stat-number text-xl text-[#7f8c94]">{i+1}</b><div><b>{r.manager.displayName}</b><p className="text-xs text-[#7d8a92]">Demo Team Name</p></div><b>{r.wins}-{r.losses}</b><span className="w-16 text-right text-xs text-[#9eabb3]">{r.points}</span></div>)}</div></div><div><SectionHeading kicker="Week 11 spotlight">Featured Matchup</SectionHeading><div className="surface p-7"><span className="demo-badge">Demo matchup</span><div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-4 text-center"><div><p className="display text-3xl">Heider</p><b className="stat-number text-5xl">142.6</b></div><span className="text-[#6f7c84]">VS</span><div><p className="display text-3xl">Leslie</p><b className="stat-number text-5xl">138.2</b></div></div><p className="mt-8 border-t border-[#283640] pt-5 text-sm leading-6 text-[#9ba7af]">A projected four-point collision between longtime contenders. Live matchup context will be sourced from ESPN.</p></div><div className="mt-6 grid grid-cols-2 gap-4"><DataCard label="Title odds" value="24%" detail="Demo model" tone="gold"/><DataCard label="Playoff odds" value="71%" detail="Demo model"/></div></div></div>
    <div className="mt-14 grid gap-5 md:grid-cols-3"><article className="surface p-6"><p className="eyebrow">Featured rivalry</p><h3 className="display mt-4 text-3xl">Leafstedt vs. Stalp</h3><p className="mt-3 text-sm text-[#95a2aa]">The all-time series deserves its own file.</p></article><article className="surface p-6"><p className="eyebrow">Record watch</p><h3 className="display mt-4 text-3xl">A new high-water mark?</h3><p className="mt-3 text-sm text-[#95a2aa]">Verified league records will populate after import.</p></article><article className="surface p-6"><p className="eyebrow">From the desk</p><h3 className="display mt-4 text-3xl">Week 11 recap</h3><p className="mt-3 text-sm text-[#95a2aa]">Commissioner recaps have a permanent home.</p></article></div>
  </section>
  </> }
