import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { cbaData } from "@/data/real";
import { formatStatValue } from "@/lib/format-stat";

export const metadata={title:"Record Book"};
const value=(record:{value:number|string;format:Parameters<typeof formatStatValue>[1]})=>formatStatValue(record.value,record.format);

export default function Page(){return <><PageHero eyebrow="League records" title="Record Book" intro="The best, worst, closest, and most ridiculous eligible marks in CBA history."/><section className="container"><div className="grid gap-4 md:grid-cols-2">{cbaData.records.map((record,index)=><article className="surface p-6" key={record.label}><p className="eyebrow">Record {String(index+1).padStart(2,"0")}</p><h2 className="mt-5 text-xl font-bold">{record.label}</h2><p className="stat-number mt-4 text-4xl text-[#dfb65f]">{value(record)}</p><p className="mt-2 text-sm text-[#929ba5]">{record.managerName}{record.year?` · ${record.year}${record.week?` Week ${record.week}`:""}`:""}</p></article>)}</div><div className="mt-16"><SectionHeading kicker="Punishment Bracket">Hall of Shame</SectionHeading><p className="mb-6 max-w-3xl text-sm leading-7 text-[#9da5ae]">Punishment records are calculated only from ESPN&apos;s losers consolation ladder. They stay completely separate from eligible regular-season and championship-playoff records.</p><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cbaData.punishmentRecords.map((record,index)=><article className="surface border-[#49343a] p-6" key={record.label}><p className="eyebrow text-[#c48a83]">Shame {String(index+1).padStart(2,"0")}</p><h2 className="mt-5 text-xl font-bold">{record.label}</h2><p className="stat-number mt-4 text-4xl text-[#d5a0a0]">{value(record)}</p><p className="mt-2 text-sm font-bold">{record.managerName}</p><p className="mt-2 text-xs leading-5 text-[#93868a]">{record.detail}{record.year&&record.week?` · ${record.year} Week ${record.week}`:""}</p></article>)}</div></div></section></>}
